# action.yml
name: 'Publish to Sharepoint'
description: 'Create an archive of the repository (if needed) and upload it to a Sharepoint online via client id and secret'
author: 'Olivier Brassard & Daniel Monaghan'
branding:
  icon: 'upload-cloud'  
  color: 'green'
inputs:
  site_url: 
    description: 'The Sharepoint site url'
    required: true
  sharepoint_client_id: 
    description: 'Client ID to use for authentication'
    required: true
  sharepoint_client_secret: 
    description: 'Client Secret to use for authentication'
    required: true
  library_folder: 
    description: 'The path where to upload the archive in the library'
    required: true
    default: "Shared documents"
  file_path: 
    description: 'To upload a specific file(s) instead of the whole repo, specify the path/glob here'
    required: false
  base_path: 
    description: 'When using a glob in file_path, preserve directory structure relative to this base path'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SITE_URL : ${{ inputs.site_url }}
    CLIENTID : ${{ inputs.sharepoint_client_id }}
    CLIENTSECRET: ${{ inputs.sharepoint_client_secret }}
    LIB_FOLDER : ${{ inputs.library_folder }}
    FILE_PATH : ${{ inputs.file_path }}
    BASE_PATH : ${{ inputs.base_path }}
