# action.yml
name: 'Publish to Sharepoint'
description: 'Create a archive of the repository and upload it to a Sharepoint online via client id and secret'
author: 'Daniel Monaghan'
branding:
  icon: 'upload-cloud'  
  color: 'green'
inputs:
  site_url: 
    description: 'The Sharepoint site url'
    required: true
  sharepoint_user: 
    description: 'User name to use for authentication'
    required: true
  sharepoint_password: 
    description: 'Password to use for authentication'
    required: true
  library_folder: 
    description: 'The path where to upload the archive in the library'
    required: true
    default: "Shared documents"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SITE_URL : ${{ inputs.site_url }}
    CLIENTID : ${{ inputs.sharepoint_client_id }}
    CLIENTSECRET: ${{ inputs.sharepoint_client_secret }}
    LIB_FOLDER : ${{ inputs.library_folder }}
