name: 'Sharepoint Sync'

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:  
    
    - name: Cloning repo
      uses: actions/checkout@v3

    - name: Publish to Sharepoint
      env:
        CLIENTID: ${{ secrets.SHAREPOINT_SOFTWARE_PLAYBOOK_CLIENTID }}
        CLIENTSECRET: ${{ secrets.SHAREPOINT_SOFTWARE_PLAYBOOK_CLIENTSECRET }}
      run: |
        sudo apt install npm
        npm install
        node ./index.js
        
